---
- name: enable ospfv3 rid
  ios_config:
    parents: ipv6 router ospf {{ ipv6routing.pid }}
    lines:
      - router-id {{ ipv6routing.rid }}
- name: enable ospfv3 passive-interface
  ios_config:
    parents: ipv6 router ospf {{ ipv6routing.pid }}
    lines:
      - passive-interface {{ item }}
  with_items:
    - "{{ ipv6routing.passive }}"
  when: ipv6routing.passive is defined
- name: enable ospfv3 on interfaces
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - "ipv6 ospf {{ ipv6routing.pid }} area {{ item.area }}"
  with_items:
      - "{{ ospfv3 }}"
