---
- name: "Stop GNS3 topology"
  hosts: localhost
  gather_facts: False
  vars:
      project_name: 'ansible-ccna-model'
      limit: 10
      gns3_server: '172.16.253.1:3080'
  tasks:
    - name: "get gns3 projects"
      uri:
        url: http://{{ gns3_server }}/v2/projects
        method: GET
      register: projects
    - name: "set the project id"
      set_fact:
        project_id: "{{ item.project_id }}"
      when: item.name == project_name
      loop: "{{ projects.json }}"
    - name: "open the project"
      uri:
        url: http://{{ gns3_server }}/v2/projects/{{ project_id }}/open
        status_code: 201,404
        method: POST
      register: result
    - debug:
        msg: "The project has been opened (status code {{ result.status }})"
      when: result.status == 201
    - fail:
        msg: "The project doesn’t exist (status code {{ result.status }})"
      when: result.status == 404
    - name: "cpu load limit check"
      uri:
        url: http://{{ gns3_server }}/v2/computes
        method: GET
        return_content: yes
      register: compute
      until: compute.json[0].cpu_usage_percent <= limit
      retries: 18
      delay: 5
    - name: "stop the project"
      uri:
        url: http://{{ gns3_server }}/v2/projects/{{ project_id }}/nodes/stop
        status_code: 204,400,404
        method: POST
      register: result
    - debug:
        msg: "All nodes stopped (status code {{ result.status }})"
      when: result.status == 204
    - fail:
        msg: "Invalid request (status code {{ result.status }})"
      when: result.status == 400
    - fail:
        msg: "Instance doesn’t exist (status code {{ result.status }})"
      when: result.status == 404
    - name: "close the project"
      uri:
        url: http://{{ gns3_server }}/v2/projects/{{ project_id }}/close
        status_code: 204, 404
        method: POST
      register: result
    - debug:
        msg: "The project has been closed (status code {{ result.status }})"
      when: result.status == 204
    - fail:
        msg: "The project doesn’t exist (status code {{ result.status }})"
      when: result.status == 404
