---
- name: "print df -Th"
  hosts: all
  gather_facts: True
  tasks:
    - shell: df -T | grep 'root' | awk '{print $3}'
      register: df_total
    - debug:
        msg: "{{ df_total.stdout_lines }}"
