---
- name: enable eigrp ipv6 rid
  ios_config:
    parents: ipv6 router eigrp {{ ipv6routing.as }}
    lines:
      - router-id {{ ipv6routing.rid }}
- name: enable eigrp ipv6 passive-interface
  ios_config:
    parents: ipv6 router eigrp {{ ipv6routing.as }}
    lines:
      - passive-interface {{ item }}
  with_items:
    - "{{ ipv6routing.passive }}"
  when: ipv6routing.passive is defined
- name: enable eigrp ipv6 on interfaces
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - ipv6 eigrp {{ ipv6routing.as }}
  with_items:
      - "{{ eigrp6 }}"
