---
- name: create stub vlan
  ios_vlan:
    vlan_id: "{{ stubvlan.id }}"
    state: present
    name: "{{ stubvlan.name }}"
  when:
    - switchports is defined
    - stubvlan is defined
- name: switchports in access on stub vlan
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - switchport mode access
      - switchport access vlan {{ stubvlan.id }}
  with_items: "{{ switchports }}"
  when:
    - switchports is defined
    - stubvlan is defined
- name: portfast and bpduguard
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - spanning-tree portfast
      - spanning-tree bpduguard enable
  with_items: "{{ switchports }}"
  when:
    - switchports is defined
    - stubvlan is defined
- name: shutdown all switchports
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - shutdown
  with_items: "{{ switchports }}"
  when:
    - switchports is defined
    - stubvlan is defined
