---
- import_tasks: enable_ospfv2.yml
  when:
    - ansible_network_os == 'ios'
    - ipv4routing is defined
    - ospfv2 is defined
  tags:
    - ospfv2
- import_tasks: static_to_ospfv2.yml
  when:
    - ansible_network_os == 'ios'
    - nat is defined
    - ipv4routing is defined
    - ospfv2 is defined
  tags:
    - ospfv2
    - static_to_ospfv2
