---
- name: enable ipv6
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - ipv6 enable
      - ipv6 address {{ item.net6 }} link-local
  with_items: "{{ interface6 }}"
  when: interface6 is defined
