---
- hosts: blocks
  gather_facts: False
  roles:
    - role: common
    - role: interface
    - role: etherchannel
    - role: vlans
    - role: spanning-tree
    - role: ipv4
    - role: ipv6
      when: protocol_ipv6 == 'enabled'
- hosts: access
  gather_facts: False
  roles:
    - role: no-ipv4-routing
- hosts: distribution
  gather_facts: False
  roles:
    - role: ipv4-routing
    - role: ipv6-routing
      when: protocol_ipv6 == 'enabled'
    - role: rip
      when: routing.ipv4 == 'rip'
    - role: eigrp4
      when: routing.ipv4 == 'eigrp4'
    - role: ospfv2
      when: routing.ipv4 == 'ospfv2'
    - role: eigrp6
      when:
        - routing.ipv6 == 'eigrp6'
        - protocol_ipv6 == 'enabled'
    - role: ospfv3
      when:
        - routing.ipv6 == 'ospfv3'
        - protocol_ipv6 == 'enabled'
    - role: dhcp-server
- hosts: blocks
  gather_facts: False
  roles:
    - role: write
