---
# https://docs.ansible.com/ansible/devel/modules/ios_l3_interface_module.html#ios-l3-interface-module
- name: configure ipv4 adresses
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - ip address {{ item.ipv4 }} {{ item.netmask }}
  with_items: "{{ interface }}"
